//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ahorro
    {
        public int Codigo { get; set; }
        public int CuentaOrigen { get; set; }
        public int Monto { get; set; }
        public byte[] Plazo { get; set; }
        public string TipoAhorro { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
    }
}
