//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificado_Deposito
    {
        public int Codigo { get; set; }
        public int CodigoUsuario { get; set; }
        public int CodigoCuenta { get; set; }
        public int CodigoMoneda { get; set; }
        public decimal Monto { get; set; }
        public string Interes { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
