//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra_Casa
    {
        public int Codigo { get; set; }
        public int CodigoUsuario { get; set; }
        public int CodigoMoneda { get; set; }
        public string TipoCasa { get; set; }
        public int TasaInteres { get; set; }
        public int ValorCasa { get; set; }
        public int Prima { get; set; }
        public int PlazoMeses { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public string Estado { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
