//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marchamo
    {
        public int idMarchamo { get; set; }
        public string idPlaca { get; set; }
        public decimal monto { get; set; }
        public decimal seguroVehiculo { get; set; }
        public decimal aporteCSV { get; set; }
        public decimal impuestoPropiedad { get; set; }
        public decimal impuestoMunicipalidad { get; set; }
        public decimal timbreFS { get; set; }
        public decimal iva { get; set; }
    }
}
